### ISSUE TITLE
Kann mich nicht anmelden

### ISSUE THREAD

**Issue by mawoka-myblock** [Kuschel-Swein/KuschelTickets#1]
Hallo, ich habe KuschelTickets frisch installiert, kann mich aber nicht mit dem Admin-Account anmelden. Ich wüsste nicht, was ich noch an Infos schreiben soll, um das Problem zu lösen.

Was mir aufgefallen ist, dass in der DB bei `kuscheltickets1_accounts` kein Eintrag vorhanden ist...

**Comment by Kuschel-Swein** [comment]
Oh, ok, das sollte nicht sein, hast du die Installation vorzeitig beendet? Wenn nein suche ich mal nach dem Fehler. Registriere dich einfach und setze die spalte `userGroup` auf 1.

**Comment by mawoka-myblock** [comment]
Ich habe die Installation mehrere male gemacht... Kann es am SMTP host liegen?

**Comment by mawoka-myblock** [comment]
Es gibt bei mir keine userGroup-eintrag in der Datenbank

**Comment by Kuschel-Swein** [comment]
ich habe die Spalte "userGroup" in der "accounts" Tabelle gemeint.

**Comment by mawoka-myblock** [comment]
Es gibt dort keinen Eintrag:
![IMG_20200618_140120](https://user-images.githubusercontent.com/66328166/85017727-42970800-b16c-11ea-9e78-996d88f2142e.jpg)

**Comment by Kuschel-Swein** [comment]
Darum sollst du dich bitte zuerst einfach registrieren.

**Comment by mawoka-myblock** [comment]
Kann KuschelTicket auch mit SSL-Verschlüsselung bei der Mail umgehen?

**Comment by Kuschel-Swein** [comment]
Wie meinst du das?

**Comment by mawoka-myblock** [comment]
Da mein richtiger mail-host nur SSL unterstützt bei der mail und als ich es als erstes damit probiert habe, bekam ich einen Error 500 also habe ich es bei einem anderen host ohne Verschlüsselung probiert, aber würde lieber meinen eigentlichen host benutzen

**Comment by Kuschel-Swein** [comment]
Hey,
sorry für die späte Rückmeldung. Ich hatte viel privates zu tun.

Eventuell hängt dein 500 Fehler mit deinen Webserver Einstellungen zusammen? Denn ich verwende für den E-Mail Versandt den PHP Mailer. Ebenfalls kann ich in meiner Lokalen Installation den Fehler nicht reproduzieren.

**Comment by Kuschel-Swein** [comment]
Da keine weiteren Nachrichten von dir kamen, schließe ich diesen Issue nun.

**Comment by axiades** [comment]
> Hey,
> sorry für die späte Rückmeldung. Ich hatte viel privates zu tun.
> 
> Eventuell hängt dein 500 Fehler mit deinen Webserver Einstellungen zusammen? Denn ich verwende für den E-Mail Versandt den PHP Mailer. Ebenfalls kann ich in meiner Lokalen Installation den Fehler nicht reproduzieren.

Wie richte ich den PHP-Mailer ein? könntest du da mal config beispiel geben ?? XD
