### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by MG-100** [Kuschel-Swein/KuschelTickets#1]
Füge bitte Responsive Support hinzu, damit die Seite auch auf dem Handy gut aussieht

**Comment by Kuschel-Swein** [comment]
Guten Tag MG-100 welche Seite betrifft dies denn? Denn bei mir passt alles. Es kann auch sein das ich das offensichtliche gerade übersehe.

**Comment by MG-100** [comment]
Bei mir passen alle Seiten nicht von der Größe her

**Comment by Kuschel-Swein** [comment]
Könntest du eventuell ein Screenshot hochladen? Denn bei mir passt es.

**Comment by Kuschel-Swein** [comment]
Da du mir nicht mehr antwortest, schließe ich diesen Issue.
