### ISSUE TITLE
Frage/Fehler

### ISSUE THREAD

**Issue by Maxim0509-byte** [Kuschel-Swein/KuschelTickets#2]
Hey,

nachdem ich die Installation des Ticketsystems abgeschlossen habe, werde ich zur Seite "https://ticket.craftinggames.de/index.php?login/" geleitet. Diese ist allerdings leer. Wie kann ich das beheben?

Liebe Grüße
Maxim0509

**Comment by Kuschel-Swein** [comment]
Hey,
wird KuschelTickets laut der "requirements.php" Datei unterstützt?

**Comment by Maxim0509-byte** [comment]
Hey,

dort steht "KuschelTickets könnte unterstützt werden, jedoch konnten einige Überprüfungen nicht ausgeführt werden" also denke ich ja, daherim Wiki steht, dass ich starten kann.

**Comment by Kuschel-Swein** [comment]
Hey,
richtig, "KuschelTickets KÖNNTE unterstützt werden" das **KÖNNTE** ist hierbei sehr wichtig. Sollten nicht alle Anforderungen überprüfbar sein - oder passen kann ich keine Funktionsfähigkeit garantieren. Ich mutmaße mal, dass die PHP Version nicht passt.

**Comment by Maxim0509-byte** [comment]
Hey,

ja, die PHP Version ist nicht die richtige. Aktuell habe ich PHP v7.3.20.

**Comment by Kuschel-Swein** [comment]
Hey,
KuschelTickets benötigt aufgrund einiger Features welche in älteren Versionen noch nicht verfügbar sind, mindestens PHP 7.4 wie auch in der "requirements.php" steht. Da du allerdings Plesk nutzt, solltest du deine PHP Version leicht ändern können.

**Comment by Maxim0509-byte** [comment]
Hey,
ich habe die Version geändert und den Installationsprozess neugestartet. Leider immernoch derselbe Fehler.

**Comment by Maxim0509-byte** [comment]
Hey,
habe nochmal alles durchlaufen. Nun geht es.

Danke!
