### ISSUE TITLE
config.php nicht vorhanden.

### ISSUE THREAD

**Issue by SaveConnectionPE** [Kuschel-Swein/KuschelTickets#3]
Guten Tag Kuschel-Swein,

Ich habe mir dein **Ticket System** gedownloaded und erfolgreich eingerichtet!
Ich habe bemerkt das keine _config.php_ im _data_ ordner vorhanden ist.

![Screenshot vom data Ordner!](https://user-images.githubusercontent.com/59916034/72663128-1b86af80-39ef-11ea-91e7-f0253d401d39.PNG)

Grüße, SaveConnectionPE ;)

**Comment by Kuschel-Swein** [comment]
Normalerweise wird die Config.php durch den Installer erstellt. Hast du diesen vollständig befolgt? Wenn dieser Fehler weiterhin bestehen sollte, gib der `installer.php` Datei die `77`7 Berechtigung.

**Comment by Kuschel-Swein** [comment]
Da du keine Reaktion zeigst, schließe ich diesen Issue nun.
